//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagementSystem.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public int SlotNumber { get; set; }
        public string PlateNumber { get; set; }
        public System.DateTime CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<int> Price { get; set; }
        public string ClientID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Slot Slot { get; set; }
    }
}
